### ISSUE TITLE
[BUG] doesnt work on 4.1

### ISSUE THREAD

**Issue by lucianomunoz** [schroef/Rigify-Save-Presets#3]
**OS:**
Windows

**Screenshots**
![image](https://github.com/schroef/Rigify-Save-Presets/assets/5134226/b0e83277-c201-466d-8de5-f0087f4a5e63)

**Comment by schroef** [comment]
Sorry, I haven't looked at this addon for years. Perhaps I can innear feature. It probably needs tons of updates since they moved to make use of bone collections

In the meantime. The core functionality of this addon actually come from the rigify addon itself. I remember I found it by accident, but it was cumbersome to use. That's why I made this addon, for easier access and easier functionality

Perhaps try to look for it and see if the function still exists if you really need it now. There should be an operator which saves a py file in the script editor. You than need to copy this code to the rigify preset folder manually

**Comment by schroef** [comment]
I just had a quick look. Its kind of hidden, also documentation did said anything about this. The old page is archived and doesnt load, only through web.archive.org did i get to see some part of the old manual

I was filling out a bug report about it. then i was checking all interaction modes and by accident i found the panel when your in armature edit mode. Super weird!!!

it still works thus and still tedious as it was hahahaha

See this panel in edit mode on the armature
![see panel in armature edit mode](https://github.com/schroef/Rigify-Save-Presets/assets/6923008/935615b5-f44e-49dc-b88d-186ad4d38b29)



See the script panel for the created py file. If you run this in from the editor it makes the meta rig. You can also save this file to the preset folder. But you need to do all of this manually
![see meta rig py in script panel](https://github.com/schroef/Rigify-Save-Presets/assets/6923008/661bd30e-c24d-4ac6-93ac-2912801ae4fa)

Sorry no fix, but it is a temporarily workaround


EDIT 2
it gets even worse. from the gecko this metarig doesnt work. You need to add an armature and delete all bones, than run the script. Its weird !

**Comment by schroef** [comment]
In this video by CGDive you can see how it works, doing it the manual way
https://www.youtube.com/watch?v=o6_AzySr64c

**Comment by schroef** [comment]
It's updated know to work on bl4.0+ see https://github.com/schroef/Rigify-Save-Presets/releases/tag/v0.1.1
